import type { Metadata } from "next";
import { Outfit, Bebas_Neue } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  weight: "400",
  subsets: ["latin"],
});

const gyst = localFont({
  src: "../../public/fonts/Gyst-Regular.woff2",
  variable: "--font-gyst",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${bebasNeue.variable} ${gyst.variable} antialiased font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
